features: []
info:
  title: Tutorial File Server
  version: 1.0.0
openapi: 3.0.0
paths:
  /chapter/{number}:
    get:
      parameters:
      - description: chapter number
        in: path
        name: number
        required: true
        schema:
          type: integer
      responses:
        '200':
          content:
            text/markdown:
              schema:
                type: string
          description: chapter file content
        '404':
          description: chapter file not found
      summary: Returns the contents of tutorial_output/chapter{number}.md
  /index:
    get:
      responses:
        '200':
          content:
            text/markdown:
              schema:
                type: string
          description: index.md content
        '404':
          description: index.md not found
      summary: Returns the contents of tutorial_output/index.md
